config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :admins
  resources :users

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy', as: :logout

  root 'comments#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
	has_secure_password
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	validates :content,
						presence: true
	validates :author,
						presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates :name,
						uniqueness: true,
						presence: true
	validates :email,
						uniqueness: true
	validates :password,
						length: { minimum: 3 }
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :set_admin, only: [:show, :edit, :update, :destroy]

  # GET /admins
  # GET /admins.json
  def index
    @admins = Admin.all
  end

  # GET /admins/1
  # GET /admins/1.json
  def show
  end

  # GET /admins/new
  def new
    @admin = Admin.new
  end

  # GET /admins/1/edit
  def edit
  end

  # POST /admins
  # POST /admins.json
  def create
    @admin = Admin.new(admin_params)

    respond_to do |format|
      if @admin.save
        format.html { redirect_to @admin, notice: 'Admin was successfully created.' }
        format.json { render :show, status: :created, location: @admin }
      else
        format.html { render :new }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admins/1
  # PATCH/PUT /admins/1.json
  def update
    respond_to do |format|
      if @admin.update(admin_params)
        format.html { redirect_to @admin, notice: 'Admin was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin }
      else
        format.html { render :edit }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/1
  # DELETE /admins/1.json
  def destroy
    @admin.destroy
    respond_to do |format|
      format.html { redirect_to admins_url, notice: 'Admin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin
      @admin = Admin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_params
      params.require(:admin).permit(:username, :password)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_admin, :current_user, :require_admin, :require_user

	def current_admin
	  @current_admin ||= Admin.find(session[:admin_id]) if session[:admin_id]
	end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

	def require_admin
		redirect_to '/login' unless current_admin
	end

  def require_user
    redirect_to '/login' unless current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.order('created_at DESC').paginate(page: params[:page], per_page: 10)
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    if current_user
      @comment = Comment.new(params.require(:comment).permit(:content))
      @comment.author = current_user.name
      @comment.phone = current_user.phone
      @comment.email = current_user.email
    else
      @comment = Comment.new(comment_params)
    end

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :phone, :email, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

  def destroy
    #@session = Session.find(params[:admin_id])
    #@session.destroy
		session[:admin_id] = nil
		session[:user_id] = nil
		redirect_to root_path
	end

	def create
		@admin = Admin.find_by_username(params[:session][:username])
		@user = User.find_by_name(params[:session][:username])
		if @admin || @user
			if @admin && @admin.authenticate(params[:session][:password])
				session[:admin_id] = @admin.id
				redirect_to comments_path
			elsif @user && @user.authenticate(params[:session][:password])
				session[:user_id] = @user.id
				redirect_to root_path
			else
				flash.now.alert = "Invalid password"
				redirect_to(:back)
			end
		else
			flash.now.alert = "Invalid username or password"
			redirect_to(:back)
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]

	def index
		@users = User.all
	end

	def show
	end

	def new
		@user = User.new
	end

	def edit
	end

	def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

	def update
		respond_to do |format|
			if @user.update(user_params)
				format.html { redirect_to @user, notice: 'User was successfully updated.' }
				format.json { render :show, status: :ok, location: @user }
			else
				format.html { render :edit }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

	private
	def user_params
		params.require(:user).permit(:name, :email, :phone, :password)
	end
  def set_user
		@user = User.find(params[:id])
	end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="form-group">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <%= f.submit "Submit", class: "btn btn-default" %>
<% end %>

app/views/admins/edit.html.erb
<% if current_admin %>
	<h1>Editing Admin</h1>
	<%= render 'form' %>
	<br>
	<%= link_to 'Show', @admin %> 
	<%= link_to 'Back', admins_path %>
<% else %>
	<% require_admin %>
<% end %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admins</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.username %></td>
        <td><%= link_to 'Show', admin %></td>
        <% if current_admin %>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_admin %>
  <%= link_to 'New Admin', new_admin_path %>
<% end %>

app/views/admins/new.html.erb
<% if current_admin %>

<h1>New Admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

<% else %>
	<% require_admin %>
<% end %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @admin.username %>
</p>

<% if current_admin %>
  <%= link_to 'Edit', edit_admin_path(@admin) %> 
<% end %>
<%= link_to 'Back', admins_path %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if !current_user %>
  <div class="form-group">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <% end %>
  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area(:content, size: "35x8") %>
  </div>
  <%= f.submit "Submit", class: "btn btn-default" %>
<% end %>

app/views/comments/edit.html.erb
<% if current_admin %>
	<h1>Editing Comment</h1>

	<%= render 'form' %>
	<%= link_to 'Show', @comment %>
	<%= link_to 'Back', comments_path %>
<% else %>
	<% require_admin %>
<% end %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<div class="sidebar col-md-4">
  <h2>Hello,
  <%=
    if current_admin
      current_admin.username
    elsif current_user
      current_user.name
    else
      " Guest"
    end
  %>
  </h2>
  <%= link_to 'New Comment', new_comment_path %><br>
  <% if current_admin || current_user %>
    <% if current_admin %>
      <%= link_to 'Show profile', admin_path(current_admin) %>
    <% else %>
      <%= link_to 'Show profile', user_path(current_user) %>
    <% end %>
      <br><%= link_to 'Log out', logout_path, method: :delete %>
  <% else %>
    <%= link_to 'Log in', login_path %><br>
    <%= link_to 'Register', new_user_path %>
  <% end %>
</div>
<div class=" col-md-8">
  <h3>Comments</h3>
  <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>
  <%= will_paginate %>
    <% @comments.each do |comment| %>
    <blockquote>
      <div class="row">
        <h6 class="text-left col-md-6 col-xs-6"><%= comment.created_at %></h6>
        <h5 class="text-right col-md-6 col-xs-6"><%= link_to 'Show', comment %>

          <% if current_admin %>
            <%= link_to 'Edit', edit_comment_path(comment) %>
            <%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </h5>
      </div>
      <p class="lead"><%= comment.content %></p>
      <footer><%= comment.author %></footer>
    </blockquote>
    <% end %>
  <%= will_paginate %>
</div>

app/views/comments/new.html.erb
<div class="jumbotron">
	<h3>New Comment</h3>

	<%= render 'form' %>
</div>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>
<% if current_admin %>
  <p>
    <strong>Phone:</strong>
    <%= @comment.phone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @comment.email %>
  </p>
<% end %>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<% if current_admin %>
  <%= link_to 'Edit', edit_comment_path(@comment) %>
<% end %>
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FeedbackForm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Admins', admins_path %></li>
        <li><%= link_to 'Users', users_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  </nav>
  <div class="container" >

    <h1 class="text-center">Feedback Form</h1>
    <%= yield %>

  </div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
	<div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
	<div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% if current_user %>
	<h1>Editing User</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @user %> |
	<%= link_to 'Back', users_path %>
<% else %>
	<% require_user %>
<% end %>

app/views/users/index.html.erb
  <p id="notice"><%= notice %></p>

  <h1>Listing Users</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
  			<th>Email</th>
  			<th>Phone</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
  				<td><%= user.email %></td>
  				<td><%= user.phone %></td>
          <td><%= link_to 'Show', user %></td>
          <% if current_admin %>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/users/new.html.erb
<div class="container">
	<h1>Register User</h1>
	<%= form_for(@user) do |f| %>
	  <% if @user.errors.any? %>
	    <div id="error_explanation">
	      <ul>
	      <% @user.errors.full_messages.each do |message| %>
	        <li class="error"><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

	  <div class="field">
	    <%= f.label :name %>
	    <%= f.text_field :name %>
	  </div>
	  <div class="field">
	    <%= f.label :email %>
	    <%= f.email_field :email %>
	  </div>
	  <div class="field">
	    <%= f.label :phone %>
	    <%= f.text_field :phone %>
	  </div>
	  <div class="field">
	    <%= f.label :password %>
	    <%= f.password_field :password %>
	  </div>
	  <div class="actions">
	    <%= f.submit "Submit", class: "submit" %>
	  </div>
	<% end %>

</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<% if current_admin %>
  <%= link_to 'Edit', edit_user_path(@user) %>
  <%= link_to 'Back', users_path %>
<% elsif @user == current_user %>
  <%= link_to 'Edit', edit_user_path(@user) %>
<% end %>